# Generated by Django 2.2.17 on 2020-11-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=30)),
                ('Number', models.IntegerField(blank=True, default='')),
                ('Grade', models.CharField(default='', max_length=30)),
                ('Cost', models.DecimalField(decimal_places=2, default='1.95', max_digits=10)),
                ('Value', models.DecimalField(decimal_places=2, default='1.95', max_digits=10)),
                ('StoryLine', models.CharField(blank=True, default='', max_length=25)),
                ('SellingNotes', models.CharField(default='', max_length=50)),
                ('CoverPic', models.ImageField(blank=True, default=False, upload_to='Comic_Pics')),
                ('BackPic', models.ImageField(blank=True, default=False, upload_to='Comic_Pics')),
                ('ContentPic', models.ImageField(blank=True, default=False, upload_to='Comic_Pics')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
