# Generated by Django 2.2.17 on 2020-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201111_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(default='Marvel', max_length=50),
        ),
    ]
