# Generated by Django 2.2.17 on 2020-11-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comicinput_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicinput',
            name='Edition',
            field=models.CharField(choices=[('Standard', 'Std'), ('Deluxe', 'Dlx'), ('News Stand', 'Nws'), ('Variant', 'Var'), ('Signed', 'Sgn'), ('Reprint', 'Rpt')], default='Std', max_length=30),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(choices=[('DC', 'DC'), ('DKH', 'DarkHorse'), ('IDC', 'IDC'), ('Image', 'Image'), ('MLB', 'Malibu'), ('Marvel', 'Marvel')], default='Marvel', max_length=20),
        ),
    ]
