# Generated by Django 2.2.17 on 2020-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201114_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicinput',
            options={'ordering': ('Title', 'Series', 'Number')},
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Edition',
            field=models.CharField(choices=[('Standard', 'Std'), ('Deluxe', 'Dlx'), ('News Stand', 'Nws'), ('Variant', 'Var'), ('Signed', 'Sgn'), ('Reprint', 'Rpt')], default='Std', max_length=4),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Grade',
            field=models.CharField(choices=[('Mint', 'MT'), ('NMPLUS', 'NM+'), ('NM', 'NM'), ('NMM', 'NM-'), ('NM/VF', 'NM/VF'), ('VF', 'VF'), ('F', 'F'), ('VG', 'VG'), ('G', 'G')], default='NM/VF', max_length=5),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(choices=[('DC', 'DC'), ('DKH', 'DarkHorse'), ('DYN', 'Dynamite'), ('IDW', 'IDW'), ('Image', 'Image'), ('MLB', 'Malibu'), ('Marvel', 'Marvel')], default='Marvel', max_length=20),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='SellingNotes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Series',
            field=models.CharField(choices=[('First', '1st'), ('Second', '2nd'), ('Third', '3rd'), ('Fourth', '4th')], default='1st', max_length=3),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
