# Generated by Django 2.2.17 on 2020-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201115_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='StoryLine',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
