# Generated by Django 2.2.17 on 2020-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201115_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='BackPic',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='Comic_Pics'),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='ContentPic',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='Comic_Pics'),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='CoverPic',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='Comic_Pics'),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='SellingNotes',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='StoryLine',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
