# Generated by Django 2.2.17 on 2020-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201115_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='Edition',
            field=models.CharField(choices=[('Standard', 'Std'), ('Deluxe', 'Dlx'), ('News Stand', 'Nws'), ('Variant', 'Var'), ('Signed', 'Sgn'), ('Reprint', 'Rpt')], default='Std', max_length=8),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Series',
            field=models.CharField(choices=[('First', '1st'), ('Second', '2nd'), ('Third', '3rd'), ('Fourth', '4th')], default='1st', max_length=8),
        ),
    ]
