# Generated by Django 2.2.17 on 2020-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201115_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicinput',
            name='SoldAmt',
            field=models.DecimalField(decimal_places=2, default='1.95', max_digits=10),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='BackPic',
            field=models.ImageField(blank=True, default='Comic_Pics/default.png', upload_to='Comic_Pics'),
        ),
    ]
