# Generated by Django 2.2.17 on 2021-01-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201219_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicinput',
            name='GradeBody',
            field=models.CharField(choices=[('CGS', 'CGS'), ('CBCS', 'CBCS'), ('PGX', 'PGX'), ('EGS', 'EGS')], default='', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='comicinput',
            name='GradeCode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Grade',
            field=models.CharField(choices=[('Mint', 'MT'), ('NMPLUS', 'NM+'), ('NM', 'NM'), ('NMM', 'NM-'), ('NM/VF', 'NM/VF'), ('VF', 'VF'), ('F', 'F'), ('VG', 'VG'), ('G', 'G'), ('P', 'P')], default='NM/VF', max_length=5),
        ),
    ]
