# Generated by Django 2.2.17 on 2021-01-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210104_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='GradeBody',
            field=models.CharField(blank=True, choices=[('CGS', 'CGS'), ('CBCS', 'CBCS'), ('PGX', 'PGX'), ('EGS', 'EGS')], default='', max_length=8, null=True),
        ),
    ]
