# Generated by Django 2.2.17 on 2021-01-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210107_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='Grade',
            field=models.CharField(choices=[('MT', 'MT'), ('NM+', 'NM+'), ('NM', 'NM'), ('NMM', 'NM-'), ('NM/VF', 'NM/VF'), ('VF+', 'VF+'), ('VF', 'VF'), ('VF-', 'VF-'), ('VF/FN', 'VF/FN'), ('FN+', 'FN+'), ('FN', 'FN'), ('FN-', 'FN-'), ('FN/VG', 'FN/VG'), ('VG', 'VG'), ('VG/GD', 'VG/GD'), ('GD', 'GD'), ('FR', 'FR'), ('PR', 'PR')], default='NM/VF', max_length=5),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(choices=[('Atlas', 'ATL'), ('Boom', 'Boom'), ('Caliber', 'CLB'), ('Charlton', 'CHR'), ('Dargaurd', 'DRG'), ('Delcourt', 'DEL'), ('Dupuis', 'DPS'), ('DC', 'DC'), ('DC Vertigo', 'DCV'), ('Dark Horse', 'DKH'), ('Dynamite', 'DYN'), ('EC', 'EC'), ('Epic', 'EPC'), ('Fantagraphics', 'FNT'), ('IDW', 'IDW'), ('Image', 'IMG'), ('Kodansha', 'KOD'), ('Malibu', 'MLB'), ('Marvel', 'Marvel'), ('Mirage', 'MRG'), ('Rebillion', 'REB'), ('Shueisha', 'SHU'), ('Shogakukan', 'SHO'), ('Soleil', 'SOL'), ('Other', 'OTH')], default='Marvel', max_length=20),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='SoldAmt',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Type',
            field=models.CharField(choices=[('Reg', 'Regular'), ('Ann', 'Annual'), ('Spc', 'Special')], default='Reg', max_length=30),
        ),
    ]
