# Generated by Django 2.2.17 on 2021-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210109_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='Edition',
            field=models.CharField(blank=True, default='Std', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Grade',
            field=models.CharField(blank=True, default='NM/VF', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='GradeBody',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(blank=True, default='Marvel', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Series',
            field=models.CharField(blank=True, default='1st', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Type',
            field=models.CharField(blank=True, default='Reg', max_length=30, null=True),
        ),
    ]
