# Generated by Django 2.2.17 on 2021-01-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210109_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicinput',
            name='Edition',
            field=models.CharField(choices=[('Stnd', 'Stnd'), ('Dlx', 'Dlx'), ('Nws', 'Nws'), ('Var', 'Var'), ('Sgn', 'Sgn'), ('Rpt', 'Rpt'), ('UK', 'UK'), ('CAD', 'CAD')], default='Std', max_length=8),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Grade',
            field=models.CharField(choices=[('MT', 'MT'), ('NM', 'NM+'), ('NM', 'NM'), ('NMM', 'NM-'), ('NM/VF', 'NM/VF'), ('VF+', 'VF+'), ('VF', 'VF'), ('VF-', 'VF-'), ('VF/FN', 'VF/FN'), ('FN+', 'FN+'), ('FN', 'FN'), ('FN-', 'FN-'), ('FN/VG', 'FN/VG'), ('VG', 'VG'), ('VG/GD', 'VG/GD'), ('GD', 'GD'), ('FR', 'FR'), ('PR', 'PR')], default='NM/VF', max_length=5),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='GradeBody',
            field=models.CharField(blank=True, choices=[('CGS', 'CGS'), ('CBCS', 'CBCS'), ('PGX', 'PGX'), ('EGS', 'EGS')], default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Publisher',
            field=models.CharField(choices=[('Atlas', 'Atlas'), ('Boom', 'Boom'), ('Caliber', 'Caliber'), ('Charlton', 'Charlton'), ('Dargaurd', 'Dargaurd'), ('Delcourt', 'Delcourt'), ('Dupuis', 'Dupuis'), ('DC', 'DC'), ('DC Vertigo', 'DC Vertigo'), ('Dark Horse', 'Dark Horse'), ('Dynamite', 'Dynamite'), ('EC', 'EC'), ('Epic', 'Epic'), ('Fantagraphics', 'Fantagraphics'), ('IDW', 'IDW'), ('Image', 'Image'), ('Kodansha', 'Kodansha'), ('Malibu', 'Malibu'), ('Marvel', 'Marvel'), ('Mirage', 'Mirage'), ('Rebillion', 'Rebillion'), ('Shueisha', 'Shueisha'), ('Shogakukan', 'Shogakukan'), ('Soleil', 'Soleil'), ('Other', 'Other')], default='Marvel', max_length=20),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Series',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th')], default='1st', max_length=8),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='Type',
            field=models.CharField(choices=[('Regular', 'Reg'), ('Annual', 'Ann'), ('Special', 'Spc')], default='Reg', max_length=30),
        ),
        migrations.AlterField(
            model_name='comicinput',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default='', null=True, verbose_name='year'),
        ),
    ]
